### PR TITLE
[fix](field) change crispy_field to tailwind_field

### PR DESCRIPTION
**Pull request by areski**
Fix issue https://github.com/django-crispy-forms/crispy-tailwind/issues/95

### CODE REVIEW

**Comment by smithdc1** [comment]
Thanks for this. At an initial glance this looks ok. 👍

Could we add some tests to show those templates no longer cause a crash?

**Comment by smithdc1** [comment]
Hi @areski --thanks for this. I've added some tests and docs for these two fields. For the field with buttons the template also needed a bit of work to make it work for tailwind. 

Do you want to take a look at this?

**Comment by areski** [comment]
Hi @smithdc1 
Thanks for jumping on this, sorry I had a busy week and didn't find the time to follow up.
really like the tests and the extra documentation.
It looks good to me!

**Comment by areski** [comment]
@smithdc1 I hate to be that guy that put pressure when you have done so much already. 
Is there anything I can do to help?
There is also some other valid PRs that might need some love.

**Comment by grundleborg** [comment]
Can this PR be merged? I've run into the same issues here and this seems to be a sensible fix.

**Comment by smithdc1** [comment]
Thanks for the PR and thanks for the review @grundleborg

**Pull request merged**
