### PR TITLE
Fix: Select attributes are leak to option children

### PR DESCRIPTION
**Pull request by hongquan**
Currently, if we pass extra attrs to `Select`, they are unexpectly copied to `<option>` children. This breaks our integration with AlpineJS:

image

### CODE REVIEW

**Comment by hongquan** [comment]
CI is failing but those issues are not related to this PR.

**Comment by hongquan** [comment]
@smithdc1 Could you take a look?

**Comment by smithdc1** [comment]
Can you rebase to `main`. Hopefully tests will then pass. 👍

**Comment by hongquan** [comment]
@smithdc1 The CI does not automatically run.

**Comment by hongquan** [comment]
Superseded by https://github.com/django-crispy-forms/crispy-tailwind/pull/150.

**Pull request closed without merging**
