### PR TITLE
#118: Added missing "disabled" attribute to select template

### PR DESCRIPTION
**Pull request by GitRon**
Partially addresses issue https://github.com/django-crispy-forms/crispy-tailwind/issues/118 and supersedes PR https://github.com/django-crispy-forms/crispy-tailwind/pull/120.

### CODE REVIEW

**Comment by GitRon** [comment]
@carltongibson As promised, I started fixing bugs 🙃

**Comment by GitRon** [comment]
@carltongibson Fixed the pipeline here as well. Would be happy to get a quick review.

**Comment by carltongibson** [comment]
@GitRon LGTM. Press on! 😅

I might have to review in batch if you're too quick 😜 — But we can always fix things/nothing really will break 🥰

**Comment by GitRon** [comment]
That's true! I think having a release and then go through the open issues and PRs should take some time but then we should have a clean slate again.

**Comment by carltongibson** [comment]
Sounds like a plan. If you can line up a release (or as close as possible) and we'll see if we can't push it out the door. 

(He says, noting to himself, that likely @smithdc1 is on the hook for it 😜)

**Pull request merged**
