### PR TITLE
#144: Tailwind CLI template discovery

### PR DESCRIPTION
**Pull request by GitRon**
Added docs about required step while installing this package.

### CODE REVIEW

**Review by carltongibson — APPROVED** [review]
Looks good. Thanks @GitRon

**Comment by GitRon** [comment]
Thx @carltongibson! Do you know why the pipeline fails? The build via makefile works locally for me... The error looks obscure to me.

**Comment by carltongibson** [comment]
[This looks likely](https://github.com/django-crispy-forms/crispy-tailwind/actions/runs/7388824723/job/20105484578?pr=145#step:4:49): 

> ERROR: sphinx 7.1.2 has requirement docutils<0.21,>=0.18.1, but you'll have docutils 0.16 which is incompatible.

**Comment by GitRon** [comment]
Oh, damn, didn't look properly. Not a Sphinx expert but I'll have a look. 👍

**Pull request merged**
