### PR TITLE
Add Django 3.2 to CI test matrix and remove 3.0

### PR DESCRIPTION
**Pull request by justinmayer**
This PR contains a few minor CI-related changes:

* Add Django 3.2 to CI test matrix
* Remove the now-unsupported Django 3.0 from the CI test matrix
* Specify Django version numbers in a slightly more-readable fashion and install them via the "compatible release" specifier
* Upgrade to "cache" v2 GitHub action

### CODE REVIEW

**Comment by justinmayer** [comment]
How fun… The form validation failure error message changed between Django 2.2 and 3.1, so updating it for 3.1+ obviously causes the test to fail for Django 2.2. Anyone have suggestions regarding how to make that test compatible with multiple Django versions?

**Comment by smithdc1** [comment]
What do you think about something like this? 

``` diff 
diff --git a/tests/test_helper.py b/tests/test_helper.py
index b141bb1..addd9ca 100644
--- a/tests/test_helper.py
+++ b/tests/test_helper.py
@@ -1,3 +1,4 @@
+import django
 from django.forms.models import formset_factory
 from django.template import Template
 from django.test import SimpleTestCase
@@ -303,6 +304,8 @@ class CrispyHelperTests(SimpleTestCase):
         formset.helper.formset_error_title = "Non Form Errors"
         formset.helper.form_tag = False
         formset.helper.layout = Layout("email")
+        if django.VERSION < (3, 2):
+            formset.non_form_errors = ["Please submit at most 2 forms."]
         html = render_crispy_form(formset)
         expected_html = """
             <div>
@@ -315,7 +318,7 @@ class CrispyHelperTests(SimpleTestCase):
                 </div>
                 <div class="border border-red-400 rounded-b bg-red-100 px-4 py-3 text-red-700">
                     <ul>
-                        <li>Please submit 2 or fewer forms.</li>
+                        <li>Please submit at most 2 forms.</li>
                     </ul>
                 </div>
             </div>
~
```

**Comment by justinmayer** [comment]
@smithdc1: Good suggestion. Thanks for that. I changed the test code here accordingly, and everything looks to be in good shape now, with all tests passing. Would you mind having another look and then merging if everything seems to be in order?

**Review by smithdc1 — APPROVED** [review]
@justinmayer -- thanks for this! 

At some point, I guess it would make sense to migrate all of the crispy-form test suites to the same style as we recently introduced in crispy-forms. But for now, I think we should have this.

**Comment by justinmayer** [comment]
Agreed — I think iterative improvement are always best. 💫

**Comment by smithdc1** [comment]
I just remembered we need to update the classifiers in `setup.py` as well.

Sorry.

**Pull request merged**
