### PR TITLE
Draft custom css docs

### PR DESCRIPTION
**Pull request by smithdc1**
The initial draft, still some items to be completed.

### CODE REVIEW

**Comment by GitRon** [comment]
Hi @smithdc1 

how can we get this merged? Is this still relevant? What's the status? Could we get it shipped? Even if it's not covering all cases?

Best  
Ronny

**Comment by smithdc1** [comment]
Yes. Likely some of this is still useful. Maybe it could be chopped at line 68 to get something in. More could be added later.

**Comment by GitRon** [comment]
Hi @smithdc1 

great! Would you mind updating the PR so we can ship your improvements to the crowd? 🙂 

Best  
Ronny

**Comment by GitRon** [comment]
Copied the parts according to @smithdc1 in new PR: https://github.com/django-crispy-forms/crispy-tailwind/pull/157. Closing this one therefore.

**Pull request closed without merging**
