### PR TITLE
Django 4.0 Support (formerly fix CheckboxSelectMultiple widget)

### LINKED ISSUE #115: Widget CheckboxSelectMultiple is displayed as a RadioSelect
When specifying the a form field to use CheckboxSelectMultiple, the HTML for RadioSelect is generated instead incorrectly.

Note: seems to be a Django 4.0 specific bug.

### PR DESCRIPTION
**Pull request by grundleborg**
Because this is a subclass of `RadioSelect`, the check for `is_radioselect`
needs to come *after* the check for `is_checkboxselectmultiple` otherwise
the radio widget will always be shown instead.

Fixes #115

### CODE REVIEW

**Comment by smithdc1** [comment]
Thanks for this. 👍 

Yes, this changed in Django 4.0, see https://github.com/django/django/commit/b9e872b59329393f615c440c54f632a49ab05b78

Could you add a test for this? I'd like to have a test to ensure we continue to support Django 3.2.

**Comment by grundleborg** [comment]
Yes happy to add a test - I'll update this PR.

I'm finding, though, that the current test suite already has some failures with Django 4.x - I'll see if I can send a separate PR for that first.

**Comment by grundleborg** [comment]
Actually, on closer inspection it turns out there was already a test for this, which was failing on Django 4.0. I've changed the CI to include Django 4.0 and fixed the other tests that were broken and included it all in this PR.

**Comment by grundleborg** [comment]
@smithdc1 would you mind approving the updates to this PR for the CI to run when you have a moment? I think this should fix all the django 4.0 issues now (including the original one I reported with CheckboxSelectMultiple).

**Comment by grundleborg** [comment]
Ah sorry, I messed up in the CI config - this time it really should work!

**Comment by smithdc1** [comment]
Thanks for the updates. Could you also update the `setup.py` file to update the classifiers for the newly supported versions? 

Thanks again.

**Comment by grundleborg** [comment]
Ah yeah, I forgot about that - now added to the PR.

**Comment by smithdc1** [comment]
Thanks for pushing this along. I've pushed a few edits to bump versions of other items across the package. Let's see what the tests says.

**Comment by smithdc1** [comment]
@grundleborg thank you for all of your efforts. 🏅

**Comment by grundleborg** [comment]
You're welcome - it's a very useful library so thank you for creating it.

**Pull request merged**
