### PR TITLE
pin requirements

### LINKED ISSUE #104: Error when following the contributing  process
Looking to add a documentation PR I did the following:

forked and cloned
python -m venv venv
source ./venv/bin/activate
(venv) pip install -r requirements.txt

image

Looking at the requirements file there isn't any pinning. 

Will get a working version and then pin?

### PR DESCRIPTION
**Pull request by chriswedgwood**
This wil resolve #104 

The issue was with sphinx-rtd-theme. Its latest version requires docutils < 0.17

sphinx-rtd-theme==0.5.1 does not raise an error

### CODE REVIEW

**Review by carltongibson — COMMENTED** [review]
In general I like to keep the dev dependencies unpinned, unless one is creating a specific problem (like here). 

I then pin that one, with a link to a tracking issue upstream, so that it's easy to check if it can be unpinned yet. 

You get the odd breakage this way, but it serves as a notification of upstream issues, and it stops you hitting an unexpected (hard) break when the deps haven't been touched for two years and suddenly you have a lot of work to do. 

Does that make sense?

**Comment by chriswedgwood** [comment]
> In general I like to keep the dev dependencies unpinned, unless one is creating a specific problem (like here).
> 
> I then pin that one, with a link to a tracking issue upstream, so that it's easy to check if it can be unpinned yet.
> 
> You get the odd breakage this way, but it serves as a notification of upstream issues, and it stops you hitting an unexpected (hard) break when the deps haven't been touched for two years and suddenly you have a lot of work to do.
> 
> Does that make sense?

Yes that makes , I wasn't sure if what I was doing was good practice or not. Will update PR

**Comment by blasferna** [comment]
Taking advantage of this change, they can update the version of crispy-forms? from `django-crispy-forms ~= 1.11.0` to `django-crispy-forms ~= 1.12.0`. I need some new features of the new version to complete the #99.

**Comment by smithdc1** [comment]
Thank you Chris! 👍

**Pull request merged**
