### PR TITLE
#158: Optimise CI linting

### PR DESCRIPTION
**Pull request by GitRon**

### CODE REVIEW

**Review by carltongibson — COMMENTED** [review]
Looks good.

**Comment by justinmayer** [comment]
Nice work. We should probably add the new job to the “needs” section of the deploy job.

**Comment by GitRon** [comment]
You are right! I just fixed it! Thx for your review!

**Comment by GitRon** [comment]
Pipeline passes, I'll merge this since this is a benefit to the project. Will keep the ticket open for the DjHTML linter but I'll add this one once #153 is through, since I don't want to introduce too many merge conflicts.

**Pull request merged**
