### PR TITLE
Added test coverage reporting

### PR DESCRIPTION
**Pull request by smithdc1**
🤞 CodeCov will respond.

### CODE REVIEW

**Comment by smithdc1** [comment]
I've tried to add coverage to the templates, as that is mostly what this package will be. 

This isn't currently working as expected 😕 

- `Coverage Report` gives coverage for all the files (incl. templates) (detail in GH Action logs)
- They are in the current working directory (detail in GH Action logs)
- But are not appearing in [codecov](https://codecov.io/gh/smithdc1/crispy-tailwind/tree/a005fc543acfa2c9c8ce16b4175cc8d349afe430)
- The [Upload file](https://codecov.io/codecov/v4/raw/2020-04-28/0E645772ADA1EF33456013A45A802AB8/a005fc543acfa2c9c8ce16b4175cc8d349afe430/4b1022f2-c273-45ca-a5b0-040669a9777d.txt) shows coverage data for templates... but files are missing from the network section at the top. 🤷 

May need to ask codecov support, unless anyone has any ideas?

**Comment by carltongibson** [comment]
> ...unless anyone has any ideas?

None immediately, sorry. 🙂 — I'd need to look into it.

**Comment by smithdc1** [comment]
> 
> None immediately, sorry. 🙂 — I'd need to look into it.

I've asked codecov support, let's see what they say. 

https://community.codecov.io/t/missing-coverage-data/1357

**Comment by thomasrockhu** [comment]
Hi, Tom from Codecov here, sorry that it's been taking a while for us to get back to you. I'll get back to you on the community thread today.

**Comment by smithdc1** [comment]
Hi @thomasrockhu,

Super thanks for your help. 👏

This has worked now (https://codecov.io/gh/django-crispy-forms/crispy-tailwind/pull/5/tree?path=crispy_tailwind%2Ftemplates%2Ftailwind%2Flayout)

Although there is now a bit of work to do to with the coverage % 🙈 

p.s. using the bash uploader was easier than the github action 😄

**Comment by thomasrockhu** [comment]
Amazing! Glad it worked out for you. We currently maintain the bash uploader more, but we'd love to get feedback on the GitHub Action. What would have made using the Action easier for you?

**Comment by smithdc1** [comment]
Hi @thomasrockhu 
There may be a bit of comparing different times. GH have only recently released the API to enable uploads from public repos without a token. 

This time I needed to enable this additional setting for coverage to work on HTML. I had a quick look at the docs but couldn't see how to pass settings onto the bash uploader?

**Comment by thomasrockhu** [comment]
Yes, it's something that we are aware of and working around for. Thanks for bringing it up, I'll try to prod about passing along other arguments down from the action

**Pull request merged**
