### PR TITLE
Added support for Django 5.1.

### PR DESCRIPTION
**Pull request by smithdc1**

### CODE REVIEW

**Comment by smithdc1** [comment]
@GitRon  -- could you review? I was slightly unsure what to do with the release notes now.

**Review by GitRon — APPROVED** [review]
Ltgm

**Comment by smithdc1** [comment]
Thanks! I'll update the notes when I'm back.

See you in Vigo this week?

**Comment by GitRon** [comment]
Great! And sure thing, I'll be giving a talk on Friday - in case we don't recognize each other 😄

**Pull request merged**
