### PR TITLE
add RecaptchaV2Checkbox support (#1)

### PR DESCRIPTION
**Pull request by thelittlebug**
* add RecaptchaV2Checkbox support

### CODE REVIEW

**Review by carltongibson — COMMENTED** [review]
Hmmm. 🤔

This looks unsustainable to me...

We can't add every possible class folks want to use in here. This is something that you'd add in your own project. 

I'd lean towards a README example showing how to do that rather than adding this. 

@smithdc1 What do you think?

**Comment by smithdc1** [comment]
Yes, I agree a documentation improvement is the way to go here. 

I think there is a fair amount to do on the docs of this project generally. Needs much more on how to enable folk to customise classes and so on. 

I wonder if a faq / cookbook could be useful here, or even via GitHub discussions so folk can comment and contribute without someone having to write up into full docs. Could make maintenance easier? 🤔

**Comment by carltongibson** [comment]
Yeah, discussions are good.

**Comment by thelittlebug** [comment]
so if that is not a solution, what is a solution?

**Pull request closed without merging**
