### PR TITLE
Added support for SelectMultiple

### LINKED ISSUE #97: many to many field when being rendered from model form its being rendered without mutiple in html
i think there is bug when rendering many to many field from modelform is being rendered without mutiple in HTML.

### PR DESCRIPTION
**Pull request by blasferna**
Fixes #97 #98

### CODE REVIEW

**Review by yosefmahmoud — APPROVED** [review]

**Comment by smithdc1** [comment]
Thanks for the PR. 

Appologies for the slow uptake here. There's a new filter that has been merged into crispy-forms "core". See https://github.com/django-crispy-forms/django-crispy-forms/pull/1127 and here it is in action https://github.com/django-crispy-forms/django-crispy-forms/pull/1155. Once that PR is merged I'll issue a release so we can use it here. 

I'm hoping this filter should simplify this template significantly. Although I've not tested it would be my expecation that this style would also give us the "multiple" attribute as well.

**Comment by blasferna** [comment]
I think it's great. I'll be waiting for the notification to see how to simplify this template with the new crispy-form filter.

**Comment by blasferna** [comment]
@smithdc1 I implemented the new filter `optgroups`. The template is simpler, but I had to add the following portion in the definition of the `select`: 

1. Check if select is multiple:
```django
{% if field.field.widget.allow_multiple_selected %}multiple {% endif %}
```
2. Add required attribute:
```django
{% if field.field.required %}required {% endif%}
```

Any suggestions for improvement?

**Comment by blasferna** [comment]
Wow!, the tests failed, apparently I broke something. As I have verified, it is not so easy to include the `required` attribute. 
 
According to `Select` widget definition i need a extra check:

https://github.com/django/django/blob/3219dd3388c437b4bd869b76ddd43c9cdad05090/django/forms/widgets.py#L692-L703

**Comment by rposborne** [comment]
How can we help get this fix for #98 merged?

**Comment by smithdc1** [comment]
Hey @rposborne -- have you reviewed this, does this fix the issue for you?

**Comment by kylebradshaw** [comment]
hitting this issue in my current codebase how can I pull this solution in?

**Comment by blasferna** [comment]
Hi @GitRon,

I've been working on this pull request for a long time. It addresses some issues related to the lack of attributes in the `select`. Could you please review it?

**Comment by GitRon** [comment]
Hi @blasferna 

there seem to be some merge conflicts. Could you fix them, please? Could you tell me how to best test your changes?

Thx!

**Comment by blasferna** [comment]
Hi @GitRon,

I have decided to close this PR as I am working on a new approach that I believe will be more effective and organized. I will soon open a new PR with these changes.

**Comment by GitRon** [comment]
Alright, looking forward to it!

**Pull request closed without merging**
